# Generated by Django 5.1.4 on 2025-02-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
